### ISSUE TITLE
Cannot pipe results into another command

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-cli#28]
➜  stormpath.github.io git:(source) stormpath list applications | grep ^name
grep: _deploy: Is a directory
grep: plugins: Is a directory
grep: public: Is a directory
grep: sass: Is a directory
grep: sass-extensions: Is a directory
grep: source: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/stormpath", line 9, in <module>
    load_entry_point('stormpath-cli==0.0.1', 'console_scripts', 'stormpath')()
  File "/Library/Python/2.7/site-packages/stormpath_cli-0.0.1-py2.7.egg/stormpath_cli/main.py", line 138, in main
    result = act(res, arguments)
  File "/Library/Python/2.7/site-packages/stormpath_cli-0.0.1-py2.7.egg/stormpath_cli/actions.py", line 120, in list_resources
    output_json=args.get('--output-json'))
  File "/Library/Python/2.7/site-packages/stormpath_cli-0.0.1-py2.7.egg/stormpath_cli/output.py", line 119, in output
    _output_tsv(data, show_headers=show_headers)
  File "/Library/Python/2.7/site-packages/stormpath_cli-0.0.1-py2.7.egg/stormpath_cli/output.py", line 94, in _output_tsv
    output_row = [force_text(row[key]) for key in keys]
KeyError: u'defaultAccountStoreMapping'
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

**Comment by avojnovicDk** [comment]
I reverted the commit in which --show-headers option was removed, but when I tried using the option, it did not work as I expected. No matter what I did, column headers didn't show.
I found out that it is never really used, even though the output function has it as its param (https://github.com/stormpath/stormpath-cli/blob/ana-show-headers-back/stormpath_cli/output.py#L115) and it is passed correctly in the main.py (https://github.com/stormpath/stormpath-cli/blob/ana-show-headers-back/stormpath_cli/main.py#L154-L156).
But this output function call is used only if action returned a result (https://github.com/stormpath/stormpath-cli/blob/ana-show-headers-back/stormpath_cli/main.py#L153), and no action returns one (https://github.com/stormpath/stormpath-cli/blob/ana-show-headers-back/stormpath_cli/actions.py). Instead, they output results on their own, and in their own way: list uses --show-links and --output-json options, and create update and delete use only --output-json options.

So, I can see two possible solutions for this:
1. I just add --show-headers to all the output calls in actions.py.
2. I refactor all the actions in actions.py so they return the result instead of outputting them by themselves and output the result in main.py using all three options.

I prefer solution 2, but I don't know if there is a good reason why some actions call output function differently.
